# DB
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PW}
quarkus.datasource.jdbc.url= ${POSTGRES_JDBC_URL}

# Flyway
quarkus.flyway.locations=db/migration/postgresql

# SMTP
quarkus.mailer.from=${MAILER_FROM}
quarkus.mailer.host=${MAILER_HOST}
quarkus.mailer.port=${MAILER_PORT:465}
quarkus.mailer.username=${MAILER_USER}
quarkus.mailer.password=${MAILER_PW}
quarkus.mailer.auth-methods=LOGIN
quarkus.mailer.login=REQUIRED
quarkus.mailer.tls=true