### Register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "mail": "mail@example.com",
  "password": "securePassword"
}

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "mail": "mail@example.com",
  "password": "securePassword"
}

> {% client.global.set("auth_token", response.body.token) %}

### Update User
PUT http://localhost:8080/auth
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "firstName": "Lukas",
  "lastName": "Wigger",
  "password": "securePassword"
}

### Delete User
DELETE http://localhost:8080/auth
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "mail": "mail@example.com",
  "password": "securePassword"
}

### Refresh token
GET http://localhost:8080/auth/refresh
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Verify token
GET http://localhost:8080/auth/verify/1

### Password Reset (Request)
POST http://localhost:8080/auth/password/reset
Content-Type: application/json

{
  "mail": "mail@example.com"
}

### Password Reset (View)
GET http://localhost:8080/auth/password/reset/1

### Password Reset (Commit)
PUT http://localhost:8080/auth/password/reset/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "password": "securePassword",
  "passwordRepeat": "securePassword"
}