### Get all delegator of user
GET http://localhost:8080/sharing/delegator
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Create Shareing token
PUT http://localhost:8080/sharing/token/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Connect users
POST http://localhost:8080/sharing/token/connect/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "permissions": "ALL"
}

### Delete share
DELETE http://localhost:8080/sharing/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### Update share
PUT http://localhost:8080/sharing/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "permissions": "JOURNAL_HISTORY"
}